# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnet_link', models.CharField(max_length=300)),
                ('start_time', models.IntegerField(blank=True, default=1477426473.959032)),
                ('orignal_seeder', models.CharField(max_length=100)),
            ],
        ),
    ]
