# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlist',
            name='orignal_seeder',
        ),
        migrations.AddField(
            model_name='sharedlist',
            name='original_seeder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sharedlist',
            name='start_time',
            field=models.IntegerField(blank=True, default=1477426796.727883),
        ),
    ]
